apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fhevm.fullname" . }}-test-prep-secrets
  labels:
    {{- include "fhevm.labels" . | nindent 4 }}
type: Opaque
data:
  mnemonic: {{ .Values.testPrep.mnemonic | b64enc | quote }}
  gateway-deployer-key: {{ .Values.testPrep.gatewayDeployerKey | b64enc | quote }}
  gateway-owner-key: {{ .Values.testPrep.gatewayOwnerKey | b64enc | quote }}
  gateway-relayer-key: {{ .Values.testPrep.gatewayRelayerKey | b64enc | quote }}