{{- if .Values.testPrep.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fhevm.fullname" . }}-test-prep-keys
  labels:
    {{- include "fhevm.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.testPrep.volumes.keys.size | default "100Mi" }}
{{- end }}