apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-fhevm-validator
  labels:
    app: {{ .Release.Name }}
    component: fhevm-validator
spec:
  ports:
    {{- if .Values.fhevmValidator }}
    {{- if .Values.fhevmValidator.ports }}
    {{- range .Values.fhevmValidator.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: TCP
    {{- end }}
    {{- end }}
    {{- end }}
  selector:
    app: {{ .Release.Name }}
    component: fhevm-validator
