apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kms-validator
  labels:
    app: {{ .Release.Name }}
    component: kms-validator
spec:
  ports:
    {{- if .Values.kmsValidator }}
    {{- if .Values.kmsValidator.ports }}
    {{- range .Values.kmsValidator.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: TCP
    {{- end }}
    {{- end }}
    {{- end }}
  selector:
    app: {{ .Release.Name }}
    component: kms-validator