apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kms-core
  labels:
    app: {{ .Release.Name }}
    component: kms-core
spec:
  ports:
    {{- if .Values.kmsCore }}
    {{- if .Values.kmsCore.ports }}
    {{- range .Values.kmsCore.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: TCP
    {{- end }}
    {{- end }}
    {{- end }}
  selector:
    app: {{ .Release.Name }}
    component: kms-core