apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fhevm.fullname" . }}-test-prep-sa
  labels:
    {{- include "fhevm.labels" . | nindent 4 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "fhevm.fullname" . }}-test-prep-role
  labels:
    {{- include "fhevm.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec"]
  verbs: ["get", "list", "create"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "fhevm.fullname" . }}-test-prep-rolebinding
  labels:
    {{- include "fhevm.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "fhevm.fullname" . }}-test-prep-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "fhevm.fullname" . }}-test-prep-role
  apiGroup: rbac.authorization.k8s.io